### ISSUE TITLE
Move the project editor repository

### ISSUE THREAD

**Issue by CharliePoole** [CharliePoole/nunit-project-editor#31]
This is being done in conjunction with moving nunit-gui. See nunit/nunit-gui#204.

**Comment by jnm2** [comment]
Isn't this project entirely separate from the test runner GUI? I don't see it in nunit/nunit-gui#204.

**Comment by CharliePoole** [comment]
Yes. But it's one of the gui projects addressed in the governance issue. I started with "projects" and talked about the gui team, which covers this project as well, but when discussing the details we focused on nunit-gui as being most important.

It's not covered in nunit/nunit-gui#204 that's a separate repository, although the same team is involved. As you know from experience, I'm fanatic about sticking to the topic in a given repo or issue. 😄

**Comment by CharliePoole** [comment]
Steps to get the project editor up and running

- [ ] Use GitHub to move the repository under my personal account. GitHub will forward references.

- [ ] Invite @nunit/gui-team members who want to continue working on this as collaborators.

- [ ] Move wiki pages and create links as needed to and from the NUnit project.

- [ ] Update the ci builds so they work under the new account.

- [ ] Figure out how to handle the MyGet feeds.

**Comment by CharliePoole** [comment]
This is working. THere will be future changes, of course, but I'm closing this.
